cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/"
  DOCKER_CLI_EXPERIMENTAL: enabled

stages:
  - build
  - test
  - install
  - package
  - manifest

build_jar:
  stage: build
  image: maven:3.6.0-jdk-11-slim
  script: mvn compile
  tags:
    - docker
    - amd64

run_tests:
  stage: test
  image: maven:3.6.0-jdk-11-slim
  script: mvn test
  dependencies:
    - build_jar
  tags:
    - docker
    - amd64

install:
  stage: install
  image: maven:3.6.0-jdk-11-slim
  script: mvn install -DskipTests
  dependencies:
    - run_tests
  artifacts:
    paths:
      - target/*.jar
  tags:
    - docker
    - amd64

docker_push_amd64:
  stage: package
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - install
  tags:
    - docker
    - amd64

docker_push_arm64:
  stage: package
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-arm64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - install
  tags:
    - docker
    - arm64

docker_manifest:
  stage: manifest
  image: docker:18.09.7
  services:
    - docker:18.09.7-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TAG_ARM64: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-arm64
    IMAGE_TAG_AMD64: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker manifest create $IMAGE_TAG $IMAGE_TAG_AMD64 $IMAGE_TAG_ARM64
    - docker manifest push $IMAGE_TAG
  dependencies:
    - docker_push_arm64
    - docker_push_amd64
  tags:
    - docker
    - amd64
